- name: Install remi repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: latest
    disable_gpg_check: true

- name: Enabling remi module
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: latest

- name: Changing listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Changing the another listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting and Enabling {{ component }} server
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
