- name: Downloading Mongodb Repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing Mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: latest

- name: Changing listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting and Enabling Mongodb server
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes