- name: Installing Mysql Schema
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: Loading Schema
  ansible.builtin.shell: mysql -h mysql-dev.nasreen.cloud -uroot -pRoboShop@1 < ${app_path}/schema/shipping.sql
